remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

title: Braulio Lozano Cuevas
description: Estudiante de Ciencia de Datos | Entusiasta de la IA | Profesor de Inglés | ITAM

# Redes sociales y contacto
social: #Estos son los links de las redes sociales y aparecen en la parte de abajo de la pagina
  github: BraulioLoz
  linkedin: [Braulio Lozano]
  email: [brauliozc03@gmail.com]

# Configuración del sitio
lang: es
timezone: America/Mexico_City

# Metadatos para SEO
author:
  name: Braulio Lozano Cuevas
  bio: Estudiante de Ciencia de Datos en el ITAM

# Google Analytics (opcional)
# google_analytics: [tu-id-de-tracking]

# Add these to your existing _config.yml
keywords: ciencia de datos, inteligencia artificial, ITAM

body {
  background-color: #1a1a1a;
  color: #ffffff;
}

.project-card {
  background: linear-gradient(145deg, #2a2a2a, #1a1a1a);
  box-shadow: 5px 5px 15px rgba(0,0,0,0.3);
}

.skill-tag {
  background: #2a2a2a;
  color: #ffffff;
  
  &:hover {
    background: #3a3a3a;
  }
}

a {
  color: #64b5f6;
  
  &:hover {
    color: #90caf9;
  }
}
